image: maven:latest

stages:
  - build
  - test
  - run

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/

run:
  stage: run
  script:
    - mvn package

build_backend:
  stage: build
  script:
    - mvn compile
  only:
    changes:
      - backEnd/**/*

build_frontend:
  stage: build
  script:
    - mvn compile
  only:
    changes:
      - frontEnd/**/*

test_job:
  stage: test
  script:
    - mvn test
  only:
    changes:
      - frontEnd/**/*
      - backEnd/**/*
