include:
  - local: '/src/main/java/backEnd/backend.gitlab-ci.yml'
  - local: '/src/main/java/frontEnd/frontend.gitlab-ci.yml'
  - local: '/src/test/java/test.gitlab-ci.yml'


stages:
  - build
  - test
  - run

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/

run:
  image: maven:latest
  stage: run
  script:
    - mvn package
