stages:
  - build
  - test
  - run

include:
  - 'src/main/java/backEnd/backend.gitlab-ci.yml'
  - 'src/main/java/frontEnd/frontend.gitlab-ci.yml'
  - 'src/test/java/test.gitlab-ci.yml'

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/

run:
  image: maven:latest
  stage: run
  script:
    - echo pwd
    - mvn package
