stages:
  - build

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/

build_frontend:
  image: maven:latest
  stage: build
  script:
    - mvn compile
  only:
    changes:
      - /src/main/java/frontEnd/**/*