image: maven:latest

stages:
  - build

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/

build_backend:
  stage: build
  script:
    - mvn compile
  only:
    changes:
      - backEnd/**/*
